# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci.com"
  version "1.34.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-darwin-amd64.tar.gz"
    sha256 "28f4581fdd7c9709a705d13dba47f554f2e8b7061fbdd343846c34388956c01a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-amd64.tar.gz"
      sha256 "b554117a7828bb987708f3d71c7ec9730bb3c19409d9aa5926686e8c37ee7e0b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-arm64.tar.gz"
        sha256 "f31e47ff78a685c00864bb73d54363b7731700c27d2df7724f12a2b2e6d58a15"
      else
        url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-armv6.tar.gz"
        sha256 "e14de24a771989598ffd078c7b45b8b9b037c6f4c15b2e500dab263a7fa4bae1"
      end
    end
  end

  def install
    bin.install "golangci-lint"
    output = Utils.popen_read("#{bin}/golangci-lint completion bash")
    (bash_completion/"golangci-lint").write output
    output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
    (zsh_completion/"_golangci-lint").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint --version"
  end
end
