# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci.com"
  version "1.34.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-darwin-amd64.tar.gz"
    sha256 "063b5a837ffd6cfb962655088ec83d5f29cd04018ff9d131b99bbe19d700ca30"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-amd64.tar.gz"
      sha256 "c124d8d06b5c75774e36aa87ed84aacd0a9d0208c6bf1ef0d823cf8de1fc65a9"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-arm64.tar.gz"
        sha256 "d0a1919533b9d68643c6aae642d7e685c39d663991eddb74cfabf9d6a85918c4"
      else
        url "https://github.com/jagrati15/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-armv6.tar.gz"
        sha256 "ef57bf5ce89d3c649b112c560c6b37a83ff2e5b724833b28621db6bb8e9393a7"
      end
    end
  end

  def install
    bin.install "golangci-lint"
    output = Utils.popen_read("#{bin}/golangci-lint completion bash")
    (bash_completion/"golangci-lint").write output
    output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
    (zsh_completion/"_golangci-lint").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint --version"
  end
end
